### ISSUE TITLE
After pi-boot-switch all other partitions are mounted...

### ISSUE THREAD

**Issue by dbddhkpde** [bablokb/pi-boot-switch#4]
Hi,
I searched for a solution to have multiple Linux installation on one SD-card.
pi-boot-switch is a fine tool which suits my needs. As a windows user with a boot manager installed I have several, primary windows boot partitions. When I boot one, the others are all hidden, so I thought this would be the same on pi-boot-switch.
When I want to switch to another Linux installation the error message show up: target partition currently mounted, aborting!

How do I do the config right, to have only the "active" partition mounted an all others / or even some of them are not?

Is it possible?
Thanks in advance
  -Stefan

P.S.: If I manually unmount the partition to switch to, everything works fine....

**Comment by bablokb** [comment]
The graphical environment of PIOS/Raspbian usually automatically mounts all partitions. You can prevent this by either adding a line in the /etc/fstab for these other system-partitions with the attribute "noauto". Or you can go to the filemanager and search for the correct option to deactivate automounting. I know it is there but since I don't use the default filemanager I cannot tell you exactly where it is.

As an alternative you can manually unmount the target partition before switching, again with the filemanager or something like

    sudo umount xxxx

You can find the correct mountpoint with "df" which lists all active mounts.

**Comment by dbddhkpde** [comment]
Thanks for your quick reply!
I think I try the noauto option!
As I said, I can manually unmount the relevant partition and than switch. I will also try the Rasbian without any desktop.
